### PR TITLE
conduits/anima

### PR DESCRIPTION
**Pull request by vely-digital**
Added conduits for shaman/druid and anima infused items

### CODE REVIEW

**Comment by vely-digital** [comment]
oh, i put anima in misc and not consumables. it's just that if my food and anima are in same tab, it makes it messy. for example I can't find my food fast if I have lots of anima items in bags.
I will move anima items to misc, because it's empty (or even make new one). 
also gona add flasks, they are not in consumable

**Comment by davidcraig** [comment]
Hi, it looks like the id's you have provided for conduits are the spell id's not the item id's, also, I have created a new file for anima items, so you may need to check this PR against the latest version.

**Comment by vely-digital** [comment]
> Hi, it looks like the id's you have provided for conduits are the spell id's not the item id's, also, I have created a new file for anima items, so you may need to check this PR against the latest version.

oh sure, it seems I messed up :(, I'll check it out when I have time.

**Comment by vely-digital** [comment]
hey david, I did some ordering for shaman/druid conduits, and fixed some duplicates inside anima/misc, it should be fine now check it out!

**Review by davidcraig — APPROVED** [review]

**Comment by davidcraig** [comment]
Amazing, thanks! :)

**Pull request merged**
